---
title: "Figure S2"
output:   
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, eval = TRUE)
```


## Figure S2

**The workingdir of this vignette is letter_Dentro_et_al_2021/paper_figures**


```{r}
library(tidyverse)
library(patchwork)


cluster_probs_41_cases <- readr::read_csv("../processed_data/cluster_probs_41cases.csv.gz")
all_PCAWG <- data.table::fread("../processed_data/maf_subclone_ccf.csv.gz", data.table = FALSE)

snvs_evo_bind <- all_PCAWG %>%  filter(Tumor_Sample_Barcode %in% (cluster_probs_41_cases$sample %>%  unique()))

snvs_evo_bind_drivers <- snvs_evo_bind %>% filter(isdriver) %>% 
  mutate(gene = paste0(gene,"_",substr(Tumor_Sample_Barcode,1,4) )) %>% 
  select(gene, Chromosome, Start_position, clonality, Tumor_Sample_Barcode) %>%  rename(chromosome = Chromosome, position = Start_position, sample = Tumor_Sample_Barcode)


snvs_evo_bind_drivers <- inner_join(cluster_probs_41_cases, snvs_evo_bind_drivers)

plot_inp <- snvs_evo_bind_drivers  %>%  select(starts_with("cluster"), gene, clonality) %>%  reshape2::melt(id.vars = c("gene", "clonality")) %>% 
  filter(variable != "cluster_4")
p4_1_1 <- ggplot(plot_inp %>%  filter(clonality == "clonal"), aes(fill = value, x = gene, y = variable)) + 
  geom_tile() + theme_minimal() + 
  scale_fill_distiller("prob",palette = "RdBu") + xlab("") + ylab("") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Clonal drivers cluster probability")

p4_1_2 <- ggplot(plot_inp %>%  filter(clonality == "subclonal"),  aes(fill = value, x = gene, y = variable)) + 
  geom_tile() + theme_minimal() + 
  scale_fill_distiller("prob",palette = "RdBu") + xlab("") + ylab("") +  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Subclonal drivers cluster probability")


p4 <- p4_1_1 / p4_1_2  + plot_annotation(tag_levels = 'a')

p4  %>%  ggsave(filename = "figure_S2.png", device = "png", plot = ., width = 12, height = 6.9)

p4
```
