---
title: "Matters arising Dentro et al."

output:   
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
---

This is the website to release all the source code attached to the paper

-- *The genetic intra-tumor heterogeneity across 2,658 human cancers remains uncharacterised*. Salvatore Milite, Marc J Williams, Jacob Househam, Timon Heide, Chela James, Riccardo Bergamin, Trevor A Graham, Andrea Sottoriva and Giulio Caravagna. 

submitted as a matters arising for the paper

-- *Characterizing genetic intra-tumor heterogeneity across 2,658 human cancer genomes*. Dentro SC, Leshchiner I, Haase K, Tarabichi M, Wintersinger J, Deshwar AG, Yu K, Rubanova Y, Macintyre G, Demeulemeester J, Vázquez-García I, Kleinheinz K, Livitz DG, Malikic S, Donmez N, Sengupta S, Anur P, Jolly C, Cmero M, Rosebrock D, Schumacher SE, Fan Y, Fittall M, Drews RM, Yao X, Watkins TBK, Lee J, Schlesner M, Zhu H, Adams DJ, McGranahan N, Swanton C, Getz G, Boutros PC, Imielinski M, Beroukhim R, Sahinalp SC, Ji Y, Peifer M, Martincorena I, Markowetz F, Mustonen V, Yuan K, Gerstung M, Spellman PT, Wang W, Morris QD, Wedge DC, Van Loo P; PCAWG Evolution and Heterogeneity Working Group and the PCAWG Consortium. Cell. 184(8) 2021:2239-2254.e39. 

We use this website to allow full reprudicibility of our analyses.

Each article provides the explanation for reproducing a particular point in the analysis. They cover the following points:

* Data generation and PCAWG CCF and clustering plots
* Germline overdispersion analysis
* WeMe consensus for beta-binomial vs binomial models
* WeMe consensus with the deconvolution methods used in the paper
* Pyclone reanalysis
* Figure generation

